### PR TITLE
Make declarative MCP server a Helidon Service

### LINKED ISSUE #158: Mcp server should support constructor injection
McpServer with constructor injection fails to build due default no-param constructor is expected in generated code: 

```java
public CliToolsMcpServer__McpServer() {
    try {
        delegate = GlobalServiceRegistry.registry().get(CliToolsMcpServer.class);
    } catch (Exception e) {
        delegate = new CliToolsMcpServer();
    }
}
```

### PR DESCRIPTION
**Pull request by tvallin**
Fixes #158

---

Updates the generated MCP server classes to look like this:

```java
@Generated(value = "io.helidon.extensions.mcp.codegen.McpCodegen", trigger = "io.helidon.extensions.mcp.tests.declarative.McpCancellationServer")
@Service.Singleton
class McpCancellationServer__McpServer implements HttpFeature {

    private McpCancellationServer delegate;

    McpCancellationServer__McpServer() {
        delegate = Services.get(McpCancellationServer.class);
    }
}
```

If the annotated server does not have a `Scope` annotation, the type mapper will make it a `Singleton`.

### CODE REVIEW

File: codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpServerTypeMapperProvider.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+                        + " has no scope annotation. Making this server a singleton.");
+                return Optional.of(TypeInfo.builder(typeInfo)
+                                           .addAnnotation(SERVICE_SINGLETON_ANNOTATION)
+                                           .build());
+            }
+            return Optional.of(typeInfo);
+        }
+
+        private boolean hasNoScopeAnnotation(TypeInfo typeInfo) {
+            return !typeInfo.hasAnnotation(SERVICE_SINGLETON)
```
Comment (tomas-langer) [inline codegen/src/main/java/io/helidon/extensions/mcp/codegen/McpServerTypeMapperProvider.java]: This is not sufficient, it may have a custom scope annotation.
